
themes = ["making bad art on mspaint",
"playing my guitar",
"analog video effects",
"liquid lights", 
"CRT glitch",
"I used to play piano", 
"picking up guitar",
"go outside with friends",
"cooking",
"cooking without a recipe",
"playing musical instruments",
"sewing",
"painting",
"Fried Calamari",
"singing and dancing",
"making my own halloween costumes",
"being a soccer fan",
"watching the euros",
"theater related stuff like acting/directing",
"Baseball",
"blåhaj",
"basketball",
"loving music more than anything else",
"Music Production (EDM)",
"working in a veterinary hospital",
"photography",
"basketball",
"vlogs",
"making videos",
"playing trumpet",
"the UCSC Wind ensemble",
"I LOVE seafood!",
"I love anime and animals",
"I like doing handcrafts",
"I like car stuff",
"I like reading manga and watching anime",
"Listening to music is my therapy",
"playing sports",
"biking",
"Art is my main hobby",
"I'm watching Twin Peaks",
"I enjoy doing digital art",
"I like listening and playing music",
"I love motorcycles",
"I love cafe racers",
"working out",
"I like to make comics",
"sports/gym",
"Origami!",
"I do really enjoy anime",
"3d printing",
"I recently got into mixology",
"I can play the drum set"]